export interface Project {
  id: string;
  slug: string;
  title: string;
  client: string;
  description: string;
  fullDescription: string;
  problem: string;
  solution: string;
  result: string;
  tags: string[];
  category: "bot" | "site" | "historico";
  stack: string[];
  deliverables: string[];
  featured: boolean;
  year: number;
  url?: string;
}

export const projects: Project[] = [

  // ===================== DESTAQUES =====================
  {
    id: "11",
    slug: "void-ticket",
    title: "VØID Ticket",
    client: "VØID Systems",
    description: "Sistema completo de tickets para Discord com dashboard web e painel de controle.",
    fullDescription: "Sistema profissional de gerenciamento de tickets para Discord com dashboard web completo. Desenvolvido para comunidades que precisam de suporte organizado e automatizado.",
    problem: "Servidores Discord precisam de um sistema profissional de tickets com painel web para gerenciamento e personalização completa.",
    solution: "Sistema completo com bot Discord, dashboard web, autenticação, banco de dados, transcripts e logs automáticos.",
    result: "Sistema em produção usado por múltiplos servidores Discord com alta estabilidade e zero necessidade de suporte.",
    tags: ["Discord", "Dashboard", "Full-Stack"],
    category: "bot",
    stack: ["Discord.js", "Next.js", "MongoDB", "TypeScript"],
    deliverables: [
      "Bot Discord completo",
      "Dashboard web com autenticação",
      "Painéis customizáveis",
      "Transcripts completos",
      "Logs detalhados",
      "Personalização completa por servidor",
    ],
    featured: true,
    year: 2025,
    url: "https://voidticket.vercel.app",
  },
  {
    id: "12",
    slug: "void-systems-site",
    title: "VØID Systems — Site",
    client: "VØID Systems",
    description: "Site oficial da VØID Systems com loja de bots, apresentação de serviços e identidade visual completa.",
    fullDescription: "Site institucional e loja da VØID Systems com design minimalista. Apresenta todos os produtos e serviços.",
    problem: "A VØID Systems precisava de uma presença online profissional para apresentar seus produtos e serviços.",
    solution: "Site completo com loja integrada, páginas de produtos e identidade visual consistente.",
    result: "Site em produção representando a VØID Systems com profissionalismo e identidade visual forte.",
    tags: ["Site", "Design", "Loja"],
    category: "site",
    stack: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    deliverables: [
      "Site institucional completo",
      "Loja de bots e serviços",
      "Design minimalista",
      "Identidade visual consistente",
    ],
    featured: true,
    year: 2025,
    url: "https://www.voidsystems.store",
  },
  {
    id: "13",
    slug: "bot-ticket-personalizado",
    title: "Bot de Ticket Personalizado",
    client: "VØID Systems — Loja",
    description: "Versão personalizada do VØID Ticket com identidade visual e configurações exclusivas para cada cliente.",
    fullDescription: "Versão customizada do sistema VØID Ticket, adaptada com as configurações específicas de cada cliente.",
    problem: "Clientes precisam de um sistema de tickets profissional com identidade própria do servidor.",
    solution: "Adaptação completa do VØID Ticket com personalização de mensagens e configurações exclusivas.",
    result: "Clientes recebem um sistema robusto e testado com identidade visual própria. Feedbacks 5/5.",
    tags: ["Discord", "Tickets"],
    category: "bot",
    stack: ["Discord.js", "Node.js", "MongoDB"],
    deliverables: [
      "Sistema de tickets completo",
      "Personalização de identidade visual",
      "Configurações exclusivas",
      "Suporte pós-entrega",
    ],
    featured: true,
    year: 2025,
  },
  {
    id: "14",
    slug: "bot-verificacao",
    title: "Bot de Verificação",
    client: "VØID Systems — Loja",
    description: "Sistema de verificação de membros com botão interativo e atribuição automática de cargo.",
    fullDescription: "Bot de verificação profissional para servidores Discord, com painel interativo e atribuição automática de cargo.",
    problem: "Servidores precisam filtrar bots e membros não verificados de forma eficiente.",
    solution: "Sistema de verificação com painel interativo e atribuição automática de cargo ao verificar.",
    result: "Segurança aumentada nos servidores com processo de verificação fluido e profissional.",
    tags: ["Discord", "Verificação"],
    category: "bot",
    stack: ["Discord.js", "Node.js"],
    deliverables: [
      "Painel de verificação interativo",
      "Atribuição automática de cargo",
      "Logs de verificação",
      "Personalização de mensagens",
    ],
    featured: true,
    year: 2025,
  },
  {
    id: "15",
    slug: "bot-registro-loja",
    title: "Bot de Registro",
    client: "VØID Systems — Loja",
    description: "Formulário de registro com aprovação da staff, atribuição de cargo e nickname automático.",
    fullDescription: "Sistema de registro completo com formulário interativo, aprovação pela staff e configuração automática de cargo e nickname.",
    problem: "Servidores precisam de um processo de entrada organizado e padronizado para novos membros.",
    solution: "Bot com formulário de registro, painel de aprovação para staff e automação de cargo e nickname.",
    result: "Entrada de membros padronizada e profissional, economizando tempo da staff.",
    tags: ["Discord", "Registro"],
    category: "bot",
    stack: ["Discord.js", "Node.js"],
    deliverables: [
      "Formulário de registro interativo",
      "Painel de aprovação para staff",
      "Atribuição automática de cargo",
      "Configuração de nickname",
    ],
    featured: true,
    year: 2025,
  },
  {
    id: "16",
    slug: "bot-sorteio",
    title: "Bot de Sorteio",
    client: "VØID Systems — Loja",
    description: "Sistema de sorteios com tempo configurável, múltiplos ganhadores e reroll automático.",
    fullDescription: "Bot de sorteios profissional com interface interativa, tempo configurável, múltiplos ganhadores e sistema de reroll.",
    problem: "Servidores precisam de um sistema de sorteios confiável, justo e fácil de usar.",
    solution: "Bot com criação de sorteios via comando, contagem regressiva, seleção aleatória de ganhadores e reroll.",
    result: "Sorteios organizados e transparentes, aumentando o engajamento dos membros.",
    tags: ["Discord", "Sorteio"],
    category: "bot",
    stack: ["Discord.js", "Node.js"],
    deliverables: [
      "Criação de sorteios via comando",
      "Contagem regressiva visual",
      "Múltiplos ganhadores configurável",
      "Sistema de reroll",
    ],
    featured: true,
    year: 2025,
  },

  // ===================== PRODUTOS VØID SYSTEMS =====================
  {
    id: "20",
    slug: "bot-anuncio",
    title: "Bot de Anúncio",
    client: "VØID Systems — Loja",
    description: "Envio de anúncios formatados para canais específicos com embed personalizado.",
    fullDescription: "Bot para envio de anúncios profissionais com embeds personalizados e formatação completa.",
    problem: "Servidores precisam de uma forma organizada e profissional de enviar comunicados.",
    solution: "Bot com comando de anúncio que gera embeds formatados e os envia para o canal configurado.",
    result: "Anúncios padronizados e profissionais, melhorando a comunicação com os membros.",
    tags: ["Discord", "Anúncio"],
    category: "bot",
    stack: ["Discord.js", "Node.js"],
    deliverables: ["Envio de anúncios com embed", "Personalização de cores e imagens", "Canal configurável"],
    featured: true,
    year: 2025,
  },
  {
    id: "21",
    slug: "bot-bate-ponto",
    title: "Bot de Bate-Ponto",
    client: "VØID Systems — Loja",
    description: "Sistema de registro de ponto para membros com histórico e relatórios.",
    fullDescription: "Bot de controle de ponto para servidores Discord, com entrada, saída e histórico de registros por membro.",
    problem: "Comunidades e empresas virtuais precisam controlar a presença dos membros de forma organizada.",
    solution: "Sistema de bate-ponto com comandos de entrada/saída, histórico individual e relatórios para a staff.",
    result: "Controle de presença organizado e automatizado, sem necessidade de planilhas manuais.",
    tags: ["Discord", "Gestão"],
    category: "bot",
    stack: ["Discord.js", "Node.js", "MongoDB"],
    deliverables: ["Registro de entrada e saída", "Histórico por membro", "Relatórios para staff"],
    featured: true,
    year: 2025,
  },
  {
    id: "22",
    slug: "bot-boas-vindas-autorole",
    title: "Bot de Boas-Vindas + Auto Role",
    client: "VØID Systems — Loja",
    description: "Mensagem de boas-vindas personalizada e atribuição automática de cargo ao entrar.",
    fullDescription: "Bot que envia mensagem de boas-vindas personalizada e atribui automaticamente o cargo configurado.",
    problem: "Servidores precisam recepcionar novos membros de forma profissional e automatizar cargos.",
    solution: "Bot com mensagem de boas-vindas customizável e sistema de auto role configurável.",
    result: "Entrada de membros padronizada e profissional, sem intervenção manual da staff.",
    tags: ["Discord", "Boas-Vindas"],
    category: "bot",
    stack: [],
    deliverables: ["Mensagem de boas-vindas personalizada", "Atribuição automática de cargo", "Canal configurável"],
    featured: false,
    year: 2025,
  },
  {
    id: "23",
    slug: "bot-registro-cla",
    title: "Bot de Registro de Clã",
    client: "VØID Systems — Loja",
    description: "Sistema de criação e registro de clãs com canais e cargos automáticos.",
    fullDescription: "Bot para criação de clãs via formulário interativo, com geração automática de canal, call e cargo do clã.",
    problem: "Servidores de jogos precisam de um sistema organizado para criação e gestão de clãs.",
    solution: "Formulário interativo que cria automaticamente canal de texto, canal de voz e cargo para cada clã.",
    result: "Criação de clãs automatizada e padronizada, economizando tempo da staff.",
    tags: ["Discord", "Clã"],
    category: "bot",
    stack: [],
    deliverables: ["Formulário de criação de clã", "Canal de texto e voz automáticos", "Cargo personalizado automático"],
    featured: false,
    year: 2025,
  },
  {
    id: "24",
    slug: "bot-status-ip",
    title: "Bot de Status de IP",
    client: "VØID Systems — Loja",
    description: "Monitoramento em tempo real de servidores de jogos com status e jogadores online.",
    fullDescription: "Bot que monitora servidores de jogos e exibe em embed atualizado automaticamente o status, jogadores online e IP.",
    problem: "Comunidades de jogos precisam saber em tempo real se o servidor está online.",
    solution: "Bot que atualiza automaticamente um embed com status, jogadores e IP do servidor.",
    result: "Informação sempre atualizada e acessível, reduzindo perguntas repetitivas no servidor.",
    tags: ["Discord", "Status"],
    category: "bot",
    stack: [],
    deliverables: ["Monitoramento em tempo real", "Embed com status e jogadores", "Atualização automática"],
    featured: false,
    year: 2025,
  },
  {
    id: "25",
    slug: "bot-cloner",
    title: "Cloner",
    client: "VØID Systems — Loja",
    description: "Clonagem completa de servidores Discord com canais, cargos e configurações.",
    fullDescription: "Bot para clonar a estrutura completa de um servidor Discord, incluindo canais, categorias, cargos e permissões.",
    problem: "Criar um servidor do zero com toda a estrutura de outro é um processo demorado e manual.",
    solution: "Bot que replica automaticamente toda a estrutura do servidor de origem para o destino.",
    result: "Economia de horas de trabalho manual na criação de servidores com estruturas complexas.",
    tags: ["Discord", "Automação"],
    category: "bot",
    stack: [],
    deliverables: ["Clonagem de canais e categorias", "Clonagem de cargos e permissões", "Configuração rápida"],
    featured: false,
    year: 2025,
  },

  // ===================== HISTÓRICO =====================
  {
    id: "30",
    slug: "zumbiland-registro-cla",
    title: "Bot de Registro de Clã",
    client: "Zumbiland",
    description: "Sistema de registro de clãs com criação automática de canais e cargos.",
    fullDescription: "Bot de registro de clãs para o servidor Zumbiland, com formulário interativo e criação automática de canal, call e cargo do clã.",
    problem: "O servidor precisava de um sistema organizado para criação e gestão de clãs.",
    solution: "Bot com formulário interativo que cria automaticamente canal, call e cargo para cada clã.",
    result: "Clãs organizados e criação automatizada sem intervenção da staff.",
    tags: ["Discord", "DayZ", "Clã"],
    category: "historico",
    stack: [],
    deliverables: ["Formulário de registro de clã", "Canal e call automáticos", "Cargo personalizado automático"],
    featured: false,
    year: 2025,
  },
  {
    id: "31",
    slug: "zumbiland-status-servidor",
    title: "Bot de Status do Servidor",
    client: "Zumbiland",
    description: "Status em tempo real do servidor DayZ com online/offline, players conectados e IP.",
    fullDescription: "Bot de status para o servidor Zumbiland que exibe em embed atualizado automaticamente se o servidor está online ou offline, quantidade de players e o IP.",
    problem: "Os jogadores precisavam de uma forma fácil de verificar o status do servidor antes de entrar.",
    solution: "Bot com embed atualizado automaticamente mostrando status, players online e IP do servidor.",
    result: "Informação sempre acessível, reduzindo perguntas repetitivas no servidor.",
    tags: ["Discord", "DayZ", "Status"],
    category: "historico",
    stack: [],
    deliverables: ["Status online/offline em tempo real", "Contador de players", "IP do servidor no embed"],
    featured: false,
    year: 2025,
  },
  {
    id: "1",
    slug: "bot-criacao-clans-dayz",
    title: "Bot de Criação de Clãs",
    client: "Projeto DayZ",
    description: "Sistema de criação automática de clãs com formulário interativo.",
    fullDescription: "Primeiro bot desenvolvido para o servidor de DayZ.",
    problem: "Necessidade de um sistema automatizado para criação de clãs.",
    solution: "Bot com formulário interativo que criava automaticamente canal, call e cargo do clã.",
    result: "Sistema funcional que automatizou a criação de clãs.",
    tags: ["Discord", "DayZ"],
    category: "historico",
    stack: [],
    deliverables: ["Formulário interativo", "Canais automáticos", "Cargo automático"],
    featured: false,
    year: 2024,
  },
  {
    id: "2",
    slug: "bot-status-servidor-dayz",
    title: "Bot de Status do Servidor",
    client: "Projeto DayZ",
    description: "Exibição em tempo real do status do servidor DayZ.",
    fullDescription: "Bot que monitora e exibe o status do servidor DayZ em tempo real.",
    problem: "Jogadores precisavam verificar se o servidor estava online.",
    solution: "Bot que exibe status, players online e IP em embed atualizado automaticamente.",
    result: "Informação sempre atualizada para os jogadores.",
    tags: ["Discord", "DayZ"],
    category: "historico",
    stack: [],
    deliverables: ["Monitoramento em tempo real", "Embed com status", "Atualização automática"],
    featured: false,
    year: 2024,
  },
  {
    id: "3",
    slug: "bot-ticket-hype",
    title: "Bot de Ticket",
    client: "Hype Otimizações",
    description: "Sistema de atendimento por categorias com logs completos.",
    fullDescription: "Sistema completo de tickets com múltiplas categorias e registro detalhado.",
    problem: "A Hype Otimizações precisava de um sistema organizado para gerenciar atendimentos.",
    solution: "Bot de tickets com categorias personalizáveis e logs automáticos.",
    result: "Organização completa do suporte. Feedback 5/5.",
    tags: ["Discord", "Tickets"],
    category: "historico",
    stack: [],
    deliverables: ["Tickets por categorias", "Painel para staff", "Logs completos"],
    featured: false,
    year: 2024,
  },
  {
    id: "4",
    slug: "bot-ticket-santos",
    title: "Bot de Ticket",
    client: "Santos Otimizações",
    description: "Ticket personalizado para suporte técnico.",
    fullDescription: "Sistema de tickets adaptado para suporte técnico da Santos Otimizações.",
    problem: "Necessidade de tickets com fluxo personalizado para suporte técnico.",
    solution: "Bot com categorias específicas e priorização automática.",
    result: "Melhoria na organização do suporte. Feedback 5/5.",
    tags: ["Discord", "Tickets"],
    category: "historico",
    stack: [],
    deliverables: ["Tickets personalizado", "Formulários por categoria", "Sistema de prioridade"],
    featured: false,
    year: 2024,
  },
  {
    id: "5",
    slug: "servidor-completo-farm-brasil",
    title: "Servidor Completo + Bot de Ticket",
    client: "Farm Brasil",
    description: "Configuração completa do servidor e sistema de tickets.",
    fullDescription: "Primeiro cliente da ZinStore. Servidor de Farming Simulator totalmente criado e configurado.",
    problem: "Farm Brasil precisava de um servidor Discord profissional do zero.",
    solution: "Servidor completo com bot de ticket, boas-vindas, autorole, sorteios e anúncios.",
    result: "Servidor funcionou 100% sem necessidade de suporte. Feedback 5/5.",
    tags: ["Discord", "Servidor"],
    category: "historico",
    stack: [],
    deliverables: ["Servidor completo", "Bot de ticket", "Boas-vindas e autorole"],
    featured: false,
    year: 2024,
  },
  {
    id: "6",
    slug: "design-loja-abel",
    title: "Design de Loja",
    client: "Abel",
    description: "Design profissional para loja Discord.",
    fullDescription: "Desenvolvimento de identidade visual e design completo para loja no Discord.",
    problem: "Abel precisava de um design profissional para sua loja.",
    solution: "Design completo com banners, layout de canais e identidade visual.",
    result: "Design profissional que elevou a percepção de qualidade da loja.",
    tags: ["Design", "Discord"],
    category: "historico",
    stack: [],
    deliverables: ["Banners personalizados", "Layout de canais", "Identidade visual"],
    featured: false,
    year: 2024,
  },
  {
    id: "7",
    slug: "bot-inscricao-vl-garcia",
    title: "Bot de Inscrição",
    client: "VL Garcia",
    description: "Sistema de perguntas sequenciais com aprovação da staff.",
    fullDescription: "Bot de inscrição com formulário interativo e aprovação manual pela staff.",
    problem: "VL Garcia precisava de um processo de inscrição estruturado.",
    solution: "Sistema com perguntas sequenciais e painel de aprovação para staff.",
    result: "Processo de inscrição organizado. Feedback 5/5.",
    tags: ["Discord", "Inscrição"],
    category: "historico",
    stack: [],
    deliverables: ["Formulário interativo", "Painel de aprovação", "Notificações via DM"],
    featured: false,
    year: 2024,
  },
  {
    id: "8",
    slug: "bot-registro-vl-garcia",
    title: "Bot de Registro",
    client: "VL Garcia",
    description: "Formulário com aprovação, cargo e nickname automático.",
    fullDescription: "Sistema de registro com formulário, aprovação da staff e configuração automática.",
    problem: "Necessidade de automatizar o processo de registro de novos membros.",
    solution: "Bot com formulário, aprovação e configuração automática de cargo e nickname.",
    result: "Automação completa do registro. Feedback 5/5.",
    tags: ["Discord", "Registro"],
    category: "historico",
    stack: [],
    deliverables: ["Formulário de registro", "Sistema de aprovação", "Cargo e nickname automáticos"],
    featured: false,
    year: 2024,
  },
  {
    id: "9",
    slug: "bot-hierarquia-vl-garcia",
    title: "Bot de Hierarquia",
    client: "VL Garcia",
    description: "Sistema de cargos configurados com lista de membros.",
    fullDescription: "Bot para gerenciamento de hierarquia com visualização de membros por cargo.",
    problem: "VL Garcia precisava visualizar e gerenciar a hierarquia de cargos.",
    solution: "Sistema que exibe a hierarquia completa e lista membros por cargo.",
    result: "Gestão simplificada da hierarquia. Feedback 5/5.",
    tags: ["Discord", "Hierarquia"],
    category: "historico",
    stack: [],
    deliverables: ["Visualização de hierarquia", "Lista por cargo", "Promoção/rebaixamento"],
    featured: false,
    year: 2024,
  },
  {
    id: "10",
    slug: "bot-geral-vl-garcia",
    title: "Bot Geral",
    client: "VL Garcia",
    description: "Automações e recursos básicos de organização.",
    fullDescription: "Bot multifuncional com automações e ferramentas para organização do servidor.",
    problem: "Necessidade de um bot centralizado com múltiplas funcionalidades.",
    solution: "Bot com comandos de utilidade, boas-vindas e ferramentas de organização.",
    result: "Servidor mais dinâmico e organizado. Feedback 5/5.",
    tags: ["Discord", "Automação"],
    category: "historico",
    stack: [],
    deliverables: ["Boas-vindas", "Comandos de utilidade", "Sistema de níveis"],
    featured: false,
    year: 2024,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find(p => p.slug === slug);
}

export function getFeaturedProjects(): Project[] {
  return projects.filter(p => p.featured);
}

export function getProjectsByCategory(category: string): Project[] {
  return projects.filter(p => p.category === category);
}

export function searchProjects(query: string): Project[] {
  const lowerQuery = query.toLowerCase();
  return projects.filter(p =>
    p.title.toLowerCase().includes(lowerQuery) ||
    p.client.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery) ||
    p.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
